export { default as WelcomeScreen } from "./welcome/welcome";
export { default as LoginScreen } from "./login/login";
export { default as RegisterScreen } from "./register/register";
export { default as HomeScreen } from "./home/home";
export { default as SettingsScreen } from "./settings/settings";
export { default as ProfileScreen } from "./profile/profile";
export { default as CreatePostScreen } from "./create-post/create-post";
export { default as ChangeLanguageScreen } from "./change-language/change-lang";
export { default as ChangePasswordScreen } from "./change-password/change-pass";
